-- MySQL Script generated by MySQL Workbench
-- Wed Apr  7 11:27:02 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema monitoring
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema monitoring
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `monitoring` DEFAULT CHARACTER SET utf8 ;
USE `monitoring` ;

-- -----------------------------------------------------
-- Table `monitoring`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoring`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `settings` TEXT NULL,
  `admin` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_name` (`username` ASC),
  INDEX `idx_email` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monitoring`.`hardware`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoring`.`hardware` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cpu` TEXT NULL,
  `memory` TEXT NULL,
  `system` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monitoring`.`workers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoring`.`workers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hardware` INT NULL,
  `alias` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `alias_UNIQUE` (`alias` ASC),
  UNIQUE INDEX `hardware_UNIQUE` (`hardware` ASC),
  INDEX `idx_alias` (`alias` ASC),
  CONSTRAINT `hardware`
    FOREIGN KEY (`hardware`)
    REFERENCES `monitoring`.`hardware` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monitoring`.`measurements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoring`.`measurements` (
  `worker` INT NULL,
  `timestamp` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `cpu_temp` DOUBLE NULL,
  `cpu_utilization` INT NULL,
  `ram_utilization` INT NULL,
  `swap_utilization` INT NULL,
  INDEX `idx_worker` (`worker` ASC),
  INDEX `idx_timestamp` (`timestamp` ASC),
  CONSTRAINT `workers`
    FOREIGN KEY (`worker`)
    REFERENCES `monitoring`.`workers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
